version: '3.9'

services:

  front:
    container_name: frontend
    build:
      context: ./front
    image: img_frontend
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
    ports:
      - 3000:3000
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./back
    image: img_backend
    volumes:
      - ./back/data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
