version: '3.9'

services:

  front:
    container_name: frontend
    build:
      context: ./front
    image: img_frontend
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
    ports:
      - 3000:3000
    restart: unless-stopped

  db-server:
    container_name: db-server
    image: postgres
    ports:
    - 5432:5432
    env_file:
      - ./dockEnv/db-server.env
    volumes:
      # - ./db-data/:/var/lib/postgresql/data
      - /goinfre/$USER/db-data/:/var/lib/postgresql/data
    restart: unless-stopped

  db-client:
    container_name: db-client
    image: img_db-client
    build:
      context: ./dbserver
    ports:
      - 5050:80
    env_file:
      - ./dockEnv/db-client.env
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./back
    image: img_backend
    volumes:
      - ./back/data:/app/data
    ports:
      - 3001:3001
    depends_on:
      db-server:
        condition: service_started
    restart: unless-stopped
